server:
  port: 8080

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: store
    password: store
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    schemas: account
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect